"""patch_Post_table

Revision ID: 4725c23d441a
Revises: d167830e9cdc
Create Date: 2025-07-17 13:06:16.583300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4725c23d441a'
down_revision: Union[str, Sequence[str], None] = 'd167830e9cdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'username',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=30),
               existing_nullable=True)
    op.create_foreign_key(None, 'posts', 'users', ['username'], ['username'])
    op.drop_column('posts', 'author_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('author_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.alter_column('posts', 'username',
               existing_type=sa.String(length=30),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
